spring:
  datasource:
    username: codelex
    password: codelex
    url: jdbc:postgresql://localhost:5432/lending-app
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:/liquibase/updates.xml
    
  